### ISSUE TITLE
Additional labels & project scope

### ISSUE THREAD

**Issue by alekna** [awslabs/chalice#51] opened 2016-07-16 22:52 UTC
Hi,

Could you please create additional labels like **in-progress**, **out-of-scope** and **in-the-pipeline** so that we could have better understanding about the scope of this project.

In my opinion #49 and #41 are the most important missing features of **chalice**. Is there a consensus whether this functionality is going to be implemented or is it out of scope?

**Comment by JamieCressey** [comment] 2016-07-20 07:26
Descriptive labels would be nice

**Comment by jamesls** [comment] 2016-07-20 09:58
That sounds reasonable to me.  I'd propose:

`accepted` - A feature request that has been accepted and is something I plan on implementing.  It's within the scope of the project.
`out-of-scope` - A feature request that is out of scope for the project.  Will likely also just be closed as well.
`in-progress` - A feature request I'm working on.  I would imagine that this is really only useful for features that would take a while to implement, otherwise linking to the issue when I send a pull request would indicate I'm working on the issue.

Was there any other labels you would find useful?

**Comment by alekna** [comment] 2016-07-20 11:05
LGTM. 

Could you please add appropriate labels to #49 and #41 ?

**Comment by jamesls** [comment] 2016-07-29 17:09
I went ahead and labeled/commented on those issues.  #49 was tough because, as useful as I think they would be, I don't see a good way to fit them into the current model of chalice.  I'm opened to ideas, but for now #49 is out of scope, #41 is accepted (though a dupe of #30).

Going to go ahead and close out this issue.  Let me know if I missed anything.

**Closed by jamesls** 2016-07-29 17:09 UTC
