### ISSUE TITLE
API Gateway Enable Cores

### ISSUE THREAD

**Issue by jnordling** [awslabs/chalice#126] opened 2016-09-23 15:48 UTC
I have been using chalice for creating simple API's. Every time i deploy, I always I have to manually enable cores in the API Gateway for the API to be used by a client side application.

Am I missing something or does this level of configuration not exist? 

Thanks for the great product, I really enjoy using it chalice.

**Comment by DeviaVir** [comment] 2016-09-25 17:44
@jnordling I suspect you mean, CORS? And if so, this is a duplicate of https://github.com/awslabs/chalice/issues/70

**Comment by jamesls** [comment] 2016-09-28 00:01
Yep, I'm working on this now.  I've spec'd out what I'm working on in #70.  Let's track progress in that issue.

**Closed by jamesls** 2016-09-28 00:01 UTC
