### ISSUE TITLE
I can't deploy (but I used to be able to)

### ISSUE THREAD

**Issue by sandywater** [awslabs/chalice#71] opened 2016-07-26 19:47 UTC
``` bash
$ chalice gen-policy > .chalice/policy.json
```

``` bash
$ chalice deploy
Updating IAM policy.
Updating lambda function...
Creating deployment package.
Sending changes to lambda.
Lambda deploy done.
API Gateway rest API already found.
Deleting root resource id
Done deleting existing resources.
Traceback (most recent call last):
  File "/Users/sandy/.virtualenvs/proj-env/bin/chalice", line 11, in <module>
    sys.exit(main())
  File "/Users/sandy/.virtualenvs/proj-env/lib/python2.7/site-packages/chalice/cli/__init__.py", line 203, in main
    return cli(obj={})
  File "/Users/sandy/.virtualenvs/proj-env/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sandy/.virtualenvs/proj-env/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/sandy/.virtualenvs/proj-env/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sandy/.virtualenvs/proj-env/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sandy/.virtualenvs/proj-env/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/sandy/.virtualenvs/proj-env/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sandy/.virtualenvs/proj-env/lib/python2.7/site-packages/chalice/cli/__init__.py", line 123, in deploy
    d.deploy(ctx.obj)
  File "/Users/sandy/.virtualenvs/proj-env/lib/python2.7/site-packages/chalice/deployer.py", line 204, in deploy
    rest_api_id, region_name, stage = self._deploy_api_gateway(config)
  File "/Users/sandy/.virtualenvs/proj-env/lib/python2.7/site-packages/chalice/deployer.py", line 402, in _deploy_api_gateway
    return self._create_resources_for_api(config, rest_api_id)
  File "/Users/sandy/.virtualenvs/proj-env/lib/python2.7/site-packages/chalice/deployer.py", line 458, in _create_resources_for_api
    config['config']['lambda_arn'])
KeyError: 'lambda_arn'
```

**Comment by jamesls** [comment] 2016-07-29 17:10
Not sure how you got in an inconsistent state.  What's the contents of your `.chalice/config.json` file?  For some reason it looks like it's missing the `lambda_arn`.

**Comment by am0z** [comment] 2016-07-30 08:49
If I could just chime in here. I'm started following issues here because I can't with `chalice` cos of this problem.

`lambda_arn` is missing from `config.json` after running `$ chalice new-project`. I don't know who's to blame here. I've tried PYPI and master versions of `chalice`.

**Comment by jamesls** [comment] 2016-08-01 23:53
Ok, I think I've figured this out.  This also seems related to #29.

I believe what's happening is `chalice deploy` runs into errors whenever you have a preexisting lambda function with the same name as your app name (the name used in `chalice new-project <name>`).

I could repro this by:

* First, create a lambda function (in the console)
* Run `chalice new-project <name>`, where `<name>` is the same name you used in the lambda function.

You'll get the `lambda_arn` error.

There's a couple of related issues here, but I have an idea on how to fix this.  I'll need to keep track of the resources I create and ensure we get a unique lambda function name for chalice.

Marking as a bug and working on a fix.

**Comment by andriisoldatenko** [comment] 2017-01-12 13:18
@sandywater still reproduce?

**Comment by stealthycoin** [comment] 2017-07-06 23:55
This should be fixed by https://github.com/awslabs/chalice/commit/ed6e2656b3f71054b9f1f03934a8e3c1b42405c3

**Closed by stealthycoin** 2017-07-06 23:55 UTC
Labels: bug
