### ISSUE TITLE
Add support to run locally for development

### ISSUE THREAD

**Issue by fawzyj** [awslabs/chalice#44] opened 2016-07-13 10:04 UTC
Currently we must run `chalice deploy` to be able to test the code.
It 'll be much nicer if we can run it on local host for development and testing/

**Comment by marvinpinto** [comment] 2016-07-13 11:20
Duplicate of https://github.com/awslabs/chalice/issues/22 ?

**Comment by fawzyj** [comment] 2016-07-13 15:24
I think #22 is about running lambda function locally, while chalice is about providing web framework interface to API gateway and lambda integration.

I think that we do not need lambda or api gateway to run locally, we need chalice to have a development mode in which it runs on top of wsgi, more or less like flask.

**Comment by jamesls** [comment] 2016-08-01 23:36
I think that #22 is about a development mode that runs a local http server so you don't have to `chalice deploy` to test.  Or at least that's how I'm interpreting #22.  Let's consolidate issues and track this feature over in #22.

**Closed by jamesls** 2016-08-01 23:36 UTC
Labels: duplicate
